import { DEVICE_CONFIG_CONSTANTS } from "../configure/DeviceConfigConstants";
import FITNESS_CONSTANTS from "./FitnessConstants";
const { POOL_LENGTH_CHOICES } = DEVICE_CONFIG_CONSTANTS;
export enum SwimStrokesEnum {
  FLY = FITNESS_CONSTANTS.FLY,
  BACK = FITNESS_CONSTANTS.BACK,
  BREAST = FITNESS_CONSTANTS.BREAST,
  FREE = FITNESS_CONSTANTS.FREE,
  HEAD_UP = FITNESS_CONSTANTS.HEAD_UP,
  IM = FITNESS_CONSTANTS.IM,
  MIXED = FITNESS_CONSTANTS.MIXED,
}

export enum PoolLengthsEnum {
  NCAA = POOL_LENGTH_CHOICES.NCAA,
  OLYMPIC = POOL_LENGTH_CHOICES.OLYMPIC,
  BRITISH = POOL_LENGTH_CHOICES.BRITISH,
  THIRD_YD = POOL_LENGTH_CHOICES.THIRD_YD,
  THIRD_M = POOL_LENGTH_CHOICES.THIRD_M,
  HOME = POOL_LENGTH_CHOICES.HOME,
  SHORT = POOL_LENGTH_CHOICES.SHORT,
  TWENTY_YARD = POOL_LENGTH_CHOICES.TWENTY_YARD,
}

export type ActivityJson = {
  action: string,
  activityData: Array<any>
}

